CREATE TABLE inbound_order
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number   VARCHAR(255)                            NOT NULL,
    supplier_id    BIGINT                                  NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    total_quantity INT                                     NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    created_at     TIMESTAMP                               NOT NULL,
    processed_at   TIMESTAMP,
    updated_at     TIMESTAMP                               NOT NULL,
    created_by     VARCHAR(255)                            NOT NULL,
    updated_by     VARCHAR(255)                            NOT NULL,
    deleted        BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_inbound_order PRIMARY KEY (id)
);

CREATE TABLE inventory
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_name  VARCHAR(255)                            NOT NULL,
    item_code  VARCHAR(255)                            NOT NULL,
    quantity   INT                                     NOT NULL,
    location   VARCHAR(255)                            NOT NULL,
    qr_code    VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP                               NOT NULL,
    updated_at TIMESTAMP                               NOT NULL,
    created_by VARCHAR(255)                            NOT NULL,
    updated_by VARCHAR(255)                            NOT NULL,
    deleted    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_inventory PRIMARY KEY (id)
);

CREATE TABLE log
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action      VARCHAR(255)                            NOT NULL,
    entity_type VARCHAR(255)                            NOT NULL,
    entity_id   BIGINT                                  NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    timestamp   TIMESTAMP                               NOT NULL,
    details     CLOB,
    created_by  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_log PRIMARY KEY (id)
);

CREATE TABLE outbound_order
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number   VARCHAR(255)                            NOT NULL,
    customer_id    BIGINT                                  NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    total_quantity INT                                     NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    created_at     TIMESTAMP                               NOT NULL,
    processed_at   TIMESTAMP,
    updated_at     TIMESTAMP                               NOT NULL,
    created_by     VARCHAR(255)                            NOT NULL,
    updated_by     VARCHAR(255)                            NOT NULL,
    deleted        BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_outbound_order PRIMARY KEY (id)
);

CREATE TABLE refresh_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(500)                            NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    expiry_date TIMESTAMP                               NOT NULL,
    created_at  TIMESTAMP                               NOT NULL,
    revoked     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nickname   VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    role       VARCHAR(255),
    name       VARCHAR(255),
    created_at TIMESTAMP                               NOT NULL,
    updated_at TIMESTAMP                               NOT NULL,
    created_by VARCHAR(255)                            NOT NULL,
    updated_by VARCHAR(255)                            NOT NULL,
    deleted    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE inbound_order
    ADD CONSTRAINT uc_inbound_order_ordernumber UNIQUE (order_number);

ALTER TABLE inventory
    ADD CONSTRAINT uc_inventory_itemcode UNIQUE (item_code);

ALTER TABLE outbound_order
    ADD CONSTRAINT uc_outbound_order_ordernumber UNIQUE (order_number);

ALTER TABLE refresh_token
    ADD CONSTRAINT uc_refresh_token_token UNIQUE (token);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_nickname UNIQUE (nickname);

ALTER TABLE inbound_order
    ADD CONSTRAINT FK_INBOUND_ORDER_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE log
    ADD CONSTRAINT FK_LOG_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE outbound_order
    ADD CONSTRAINT FK_OUTBOUND_ORDER_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESH_TOKEN_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);