spring:
  config:
    import: "optional:classpath:oauth.yml" # oauth.yml 파일을 불러옵니다.
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT 설정 (개발용)
jwt:
  # 환경 변수가 없으면 기본값을 사용합니다.
  secret: ${JWT_SECRET:dGVzdFNlY3JldEtleUZvckp1bml0VGVzdGluZ1dpdGgyNTZCaXRzTGVuZ3RodGVzdFNlY3JldEtleUZvckp1bml0VGVzdGluZ1dpdGgyNTZCaXRzTGVuZ3RodGVzdFNlY3JldEtleUZvckp1bml0VGVzdGluZ1dpdGgyNTZCaXRzTGVuZ3Ro}
  expiration: 3600 # 1시간

# 로깅 설정
logging:
  level:
    com.app.server: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://db:5432/gook_prod
    driver-class-name: org.postgresql.Driver
    username: prod_user
    password: prod_pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  # JWT 설정 (운영용)
  jwt:
    # 운영 환경에서는 반드시 환경 변수로 설정해야 합니다.
    secret: ${JWT_SECRET}
    expiration: 3600 # 1시간

  # 로깅 설정
  logging:
    level:
      com.app.server: INFO
      org.springframework.security: INFO
      org.hibernate.SQL: WARN