spring:
  security:
    oauth2:
      client:
        # --------------------------------------------------
        # Google 설정 (Spring 기본 제공)
        # --------------------------------------------------
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
          # --------------------------------------------------
          # Naver 설정 (커스텀 프로바이더)
          # --------------------------------------------------
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

          # --------------------------------------------------
          # Kakao 설정 (커스텀 프로바이더)
          # --------------------------------------------------
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao

        # --------------------------------------------------
        # 각 프로바이더의 상세 정보 (Naver, Kakao는 필수)
        # --------------------------------------------------
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # Naver의 응답은 response 객체 안에 실제 정보가 있음
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # Kakao는 최상위에 id가 있음